### PR TITLE
Update MEMBERS.md

### PR DESCRIPTION
**Pull request by RakeMakes**

### CODE REVIEW

**Comment by Lillenooben** [comment]
Did you make 2 PRs?

**Comment by RakeMakes** [comment]
> Did you make 2 PRs?

Yeah, I think I mashed the PR button too much. Used the app, and couldn't see it update.

**Comment by AlexTelon** [comment]
Its unclear to me if this is a duplicate PR that should be closed or if this is something you want approved?

**Comment by RakeMakes** [comment]
No its a duplicate. So it can be removed.

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
