### PR TITLE
Sprint 1 Goals

### PR DESCRIPTION
**Pull request by GabrielAdward**

### CODE REVIEW

**Comment by Lillenooben** [comment]
@AlexTelon The comparison in "Files Changed" does not line up with the actual file updated with another squads squad goals. So Im not sure how this merge will end up. Also I see now that you have requested a review from Bruce but I already merged another one of these squad goals into the initial one.

**Comment by AlexTelon** [comment]
Oh there should be no issue to merge this. Gabriel needs to update on his end but its an small change to ensure that his teams table is added at the end applied on top of the changes you approved in the other PR.

**Comment by AlexTelon** [comment]
Maybe I will just leave these alone. But sometime I get private messages asking me to review these at which point it it's not for me to review them I assign to someone else. Bruce or you I don't particularly care about :)

**Comment by GabrielAdward** [comment]
Resolved the conflict!

**Review by Lillenooben — APPROVED** [review]

**Pull request merged**
