### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by WinterBoii**

### CODE REVIEW

**Comment by AlexTelon** [comment]
Please see the example at the top of the page. Make it a link as well.

**Comment by AlexTelon** [comment]
I'm sorry the merge you did is not what we should have. The change in the end should be "+1 -1".

If can understand the confusion, dealing with git conflicts is tricky at first. But your commit in the end should only change 1 line.

**Comment by WinterBoii** [comment]
now?
its +4 but i added space

**Comment by AlexTelon** [comment]
yes your last commit is only 1 line change. But in aggregate you have added 3 more.

image

here in github you can see that if I merge this we will add 3 empty rows for roles that have already been filled in.

You need to ensure that the code on your side is a table without these 3 extra rows.

**Comment by AlexTelon** [comment]
You could do a hard reset of your branch to "origin main"  and then do your change and force push to your WinterBoii:add_my-name branch. or create a new PR where you start over which is kidnof similar but not as neat.

**Pull request closed without merging**
